### ISSUE TITLE
Protocol Commands

### ISSUE THREAD

**Issue by CraigWhippo** [Photosynq/PhotosynQ-Documentation#3]
The entry describing the `environmental` command contains a broken link  to the old wiki describing how to create an expression.

https://help.photosynq.org/protocols/commands.html#environmental

**Comment by Ishaan28malik** [comment]
Can u please describe upon this issue 
So that I can help upon it ?

**Comment by CraigWhippo** [comment]
The link to the old wiki is DEAD.   Please either remove the link OR reinstate the tutorial on how to create an expression.

**Comment by SeBassTian23** [comment]
Thanks @CraigWhippo for finding this dead link. It is referring to an old documentation that no longer exists. I'm working on getting that part of the old documentation back into the new one.

**Comment by CraigWhippo** [comment]
@SeBassTian23, thanks for the response.  I like what you are doing with the documentation.
